[package]
name = "seshmux-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
seshmux-core = { path = "../seshmux-core" }
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
